### PR TITLE
Added an article about COVID data

### PR DESCRIPTION
**Pull request by PhilipMathieu**
Hi Prof,

I came across [this article](https://fivethirtyeight.com/features/the-covid-19-metrics-policymakers-should-be-watching-after-omicron/) this morning and thought it might be an interesting addition to the conversation. I also am trying to figure out how forking works, hence submitting this comment as a pull request.

### CODE REVIEW

**Comment by pbogden** [comment]
Nice!

Note: Your pull request created "conflicts that must be resolved". These were detected automatically. It turns out that my version of the markdown file had evolved independently of yours. Automatic merging of your edits wasn't going to work. So I just added your link to my version of the file.

That said, it's great that you're experimenting with this stuff!

**Comment by PhilipMathieu** [comment]
That of course makes sense given the timeline. If we were doing this with code in a real world scenario,

Philip
________________________________

**Comment by PhilipMathieu** [comment]
(hit send accidentally. Outlook is not great.)
In the real world scenario, how would this play out? Would I go back to my forked repository, pull your changes, and then modify my pull request?

Philip
________________________________

**Comment by pbogden** [comment]
You create a branch, perform any tests and check for conflicts if you merge.  You'd update your branch to resolve any conflicts on your end and then submit a pull request.

**Pull request closed without merging**
